# Generated by Django 6.0.3 on 2026-03-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='signature',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
